import { Request } from 'express';
import { ObjectId } from 'mongodb';
import { Skill } from './skill';

/**
 * Represents a skill that a user can add to their profile.
 * - `skillName`: The name of the skill.
 * - `endorsements`: A list of user IDs who have endorsed the skill.
 */
export interface UserSkill extends Skill {
  endorsements: string[];
  verified: boolean;
}

/**
 * Represents user credentials for authentication.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 */
export interface UserCredentials {
  username: string;
  password: string;
}

/**
 * Represents a user document, including user credentials and additional details.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `name`: The name of the user (optional).
 * - `biography`: A short description or bio of the user (optional).
 */
export interface User extends UserCredentials {
  dateJoined: Date;
  name?: string;
  biography?: string;
  skills?: UserSkill[];
}

/**
 * Represents a user document in the database.
 * - `username`: The unique username of the user.
 * - `password`: The user's password.
 * - `dateJoined`: The date when the user registered.
 * - `biography`: A short description or bio of the user (optional).
 * - `name`: The name of the user (optional).
 * - `_id`: The unique identifier for the user, generated by MongoDB.
 */
export interface DatabaseUser extends User {
  _id: ObjectId;
}

/**
 * Express request for user login, containing user credentials.
 * - `username`: The username submitted in the request (body).
 * - `password`: The password submitted in the request (body).
 * - `name`: Optional field for the user's name (body).
 * - `biography`: Optional field for biography information (body).
 */
export interface UserRequest extends Request {
  body: {
    username: string;
    password: string;
    name?: string;
    biography?: string;
  };
}

/**
 * Express request for querying a user by their username.
 * - `username`: The username provided as a route parameter.
 */
export interface UserByUsernameRequest extends Request {
  params: {
    username: string;
  };
}

/**
 * Express request for adding a skill to a user's profile.
 * - `username`: The username of the user to add the skill to (body).
 * - `skillName`: The name of the skill to add (body).
 */
export interface AddSkillToProfileRequest extends Request {
  body: {
    username: string;
    skillName: string;
  };
}

export interface VerifySkillRequest extends Request {
  body: {
    username: string;
    skillName: string;
  };
}

export interface EndorseSkillRequest extends Request {
  body: {
    username: string;
    skillName: string;
    endorser: string;
  };
}

/**
 * Represents a "safe" user object that excludes sensitive information like the password.
 */
export type SafeDatabaseUser = Omit<DatabaseUser, 'password'>;

/**
 * Represents the response for user-related operations.
 * - `SafeDatabaseUser`: A user object without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UserResponse = SafeDatabaseUser | { error: string };

/**
 * Represents the response for multiple user-related operations.
 * - `SafeDatabaseUser[]`: A list of user objects without sensitive data if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type UsersResponse = SafeDatabaseUser[] | { error: string };

/**
 * Express request for updating a user's biography.
 * - `username`: The username whose biography is being updated (body).
 * - `biography`: The new biography content to be set (body).
 */
export interface UpdateBiographyRequest extends Request {
  body: {
    username: string;
    biography: string;
  };
}

/**
 * Express request for updating a user's display name.
 * - `username`: The username whose display name is being updated (body).
 * - `name`: The new display name to be set (body).
 */
export interface UpdateDisplayNameRequest extends Request {
  body: {
    username: string;
    name: string;
  };
}

/**
 * Express request for verifying a Google token.
 * - `token`: The Google token to be verified (body).
 */
export interface VerifyGoogleTokenRequest extends Request {
  body: {
    token: string;
  };
}

/**
 * Represents the response for Google user verification.
 * - `sub`: The unique Google user ID.
 * - `email`: The user's email address.
 * - `email_verified`: Whether the email address has been verified.
 * - `name`: The user's full name.
 * - `given_name`: The user's first name.
 * - `family_name`: The user's last name.
 * - `picture`: A URL to the user's profile picture.
 * - `locale`: The user's locale (language and country).
 * @see https://developers.google.com/identity/sign-in/web/backend-auth
 */
export interface GoogleUserResponse {
  sub: string;
  email?: string;
  email_verified?: boolean;
  name?: string;
  given_name?: string;
  family_name?: string;
  picture?: string;
  locale?: string;
}

export type SafeGoogleUserResponse = GoogleUserResponse | { error: string };
